### ISSUE TITLE
Possible corruption of blob data

### ISSUE THREAD

**Issue by spodskubka** [giometrix/Xtensible.TusDotNet.Azure#12]
There is a problem in the implementation which leads to a corrupt upload.

I will try to explain it through an example:
1. A 10 MB (10 000 000 bytes) file should be uploaded in a single TUS chunk
2. A new upload is created through `AzureBlobTusStore.CreateFileAsync(...)`
   * the append blob is created
     * Blob metadata: `UploadLength = 10000000, UploadOffset = 0`
     * Blob Content-Length: `0`
3. The TUS PATCH request containing the 10 MB data reaches `AzureBlobTusStore.AppendDataAsync(...)`
   * `appendBlobClient.AppendBlockAsync(...)` is called for the first 4 MiB
     * Blob Content-Length changes to: `4194304` (metadata does not change)
4. The HTTP connection for the TUS PATCH request is killed after 5 MB are transferred
   * The `CancellationToken` is triggered, which prevents `appendBlobClient.SetMetadataAsync(...)` from being called
5. The client wants to resume the upload and performs a HEAD request to get the current upload offset
   * According to the blob metadata, offset 0 is returned although the blob already contains 4 MiB
6. The client resumes the upload and sends a TUS PATCH request, again containing all 10 MB of the upload file
   * `appendBlobClient.AppendBlockAsync(...)` is called for the first 4 MiB
     * Blob Content-Length changes to: `8388608`
   * ...
   * `appendBlobClient.AppendBlockAsync(...)` is called for the last part of the 10 MB
     * Blob Content-Length changes to: `14194304`
   * `appendBlobClient.SetMetadataAsync(...)` is called
     * Blob Metadata changes to: `UploadLength = 10000000, UploadOffset = 10000000`

The result is a corrupt blob, which contains more than `UploadLength` bytes because parts of it are duplicated.

This is my proposal for a fix:

Unless I am missing something the `UploadLength` metadata field contains redundant information (which can only be synced with the actual blob length with a delay), thus it should be dropped; instead, only the `Content-Length` of the blob should be used, because it can be trusted.
This alone would already be a big help regarding this problem.

As an additional safety net, when calling `appendBlobClient.AppendBlockAsync(...)` some `AppendBlobRequestConditions` properties should be used for validation:
`IfAppendPositionEqual` should be set to the `Upload-Offset` header value which was sent by the TUS client (i guess this would need a backwards-incompatible modification in the tusdotnet library, that value is missing in the interface).
`IfMaxSizeLessThanOrEqual` could be set to the `UploadLength` metadata property, to be on the safe side.

What do you think?

**Comment by spodskubka** [comment]
FYI, I am working on a pull request.
Should be finished tomorrow.

**Comment by giometrix** [comment]
Thanks for your bug report.

What you said makes sense on the surface, I'll need to think about it more, though if it looks like your change solves the problem, I think it'll prove out your approach.


Looking forward to the PR!

**Comment by spodskubka** [comment]
In the pull request, I did not include the `AppendBlobRequestConditions` safety net I mentioned.

It would help against corruption when multiple simultaneous "append data chunk" operations came in simultaneously for the same upload file.
However, `IfAppendPositionEqual` would be the more useful of the two, but tusdotnet doesn't make the necessary data available to use it. `IfMaxSizeLessThanOrEqual` would only help in detecting a corrupt upload at the very end, after the whole file was already uploaded, so less useful.
