### ISSUE TITLE
Allow Per Item Blob Path

### ISSUE THREAD

**Issue by evancjohnson** [giometrix/Xtensible.TusDotNet.Azure#3]
Hello @giometrix ,

I was wondering if you had considered allowing files to be added in a specific path? For example, with the user's id or a certain path in the given container.

I am more than happy to create a PR for this. You don't have any guidance for PRs or anything and if you aren't accepting any right now. Thank you for creating this library!

**Comment by giometrix** [comment]
PRs are happily accepted.

I will be on holiday til sept 5 so expect a short delay on feedback :)

**Comment by giometrix** [comment]
PRs are happily accepted.

I will be on holiday til sept 5 so expect a short delay on feedback :)

**Comment by JohnCampionJr** [comment]
I added this option on my fork.  Let me know if interested in a PR.  I also updated to .net6.0 and .net8.0 only and a few other tidying changes.

**Comment by giometrix** [comment]
@JohnCampionJr Very interested! Thank you

**Comment by JohnCampionJr** [comment]
@giometrix  Will do.  I made one other change I wanted to check.  I removed the dependency on your mockable clock for an easy 3 line bit of code as seen here:
https://ayende.com/blog/3408/dealing-with-time-in-tests

I'm not a fan of extra packages for minimal code, but I recognize its your code which is why I'm asking :)

OK if I include this in my PR or would you rather it be left alone?

**Comment by giometrix** [comment]
Go for it.  That time package is also mine 🤓 but I'm not married to it.

Also seems redundant now (https://levelup.gitconnected.com/bending-datetime-in-net-8-to-test-your-code-better-52e5cd83be4c)

**Comment by JohnCampionJr** [comment]
That's what I meant; it's your time package.  I saw the new official way too, but it feels like way too much extra code for this relatively simple, only-needed-one-place bit of code :). 

PR coming....

**Comment by giometrix** [comment]
@JohnCampionJr thanks for the PR.  nuget package incoming!
