### ISSUE TITLE
Container does not exist

### ISSUE THREAD

**Issue by Tyomnat** [giometrix/Xtensible.TusDotNet.Azure#9]
Due to the current implementation of the `EnsureContainerExistsAsync` in the case of dynamic routing (when part of the route defines the container name) with the `MapTus` implementation, it assumes that a container exists (`_containerExists`) when it does not, when a different `containerName` is used. 

IMO, this should implement some more specific check when it comes to the existence of a container, whether it be a collection of containers that are confirmed to exist or just add an `BlobContainerClient` `Exists` check to determine the need of the container creation.

**Comment by Tyomnat** [comment]
@giometrix, please review PR #10 in regards to fixing this issue.

**Comment by giometrix** [comment]
@Tyomnat latest has been pushed to nuget and will be live shortly.
